// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;
using SWRevealViewControllerBinding;

namespace SWRevealExample {
  public partial class ColorViewController : UIViewController {
    public ColorViewController(IntPtr handle)
      : base(handle) {
      LabelContent = "Unknown";
      ViewColor = UIColor.Black;
    }

    public string LabelContent { get; set; }

    public UIColor ViewColor { get; set; }

    public override void ViewDidLoad() {
      base.ViewDidLoad();
      DummyLabel.Text = "Item " + LabelContent;
      View.BackgroundColor = ViewColor;
      if (this.RevealViewController() == null)
        return;
      
      RevealButtonItem.Clicked += (sender, e) => this.RevealViewController().RevealToggleAnimated(true);
      View.AddGestureRecognizer(this.RevealViewController().PanGestureRecognizer);
    }
  }
}
