// This file has been autogenerated from a class added in the UI designer.

using System;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using SWRevealViewControllerBinding;

namespace SWRevealExample {
  public partial class MenuController : UITableViewController {
    public MenuController(IntPtr handle)
      : base(handle) {}

    public override void ViewDidLoad() {
      base.ViewDidLoad();
      var tableView = View as UITableView;
      if (tableView != null) {
        tableView.Source = new TableSource();
      }
    }

    public override void PrepareForSegue(UIStoryboardSegue segue, NSObject sender) {
      base.PrepareForSegue(segue, sender);
      var segueReveal = segue as SWRevealViewControllerSegue;
      if (segueReveal == null) {
        return;
      }
      var destinationController = segueReveal.DestinationViewController as ColorViewController;
      if (destinationController != null && sender is UITableViewCell) {
        var senderCell = sender as UITableViewCell;
        if (senderCell.ReuseIdentifier == "two") {
          destinationController.LabelContent = "2";
          destinationController.ViewColor = UIColor.Green;
        } else {
          destinationController.LabelContent = "3";
          destinationController.ViewColor = UIColor.Blue;
        }
      }
	  this.RevealViewController().PushFrontViewController(segueReveal.DestinationViewController, true);
    }
  }
}
